'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import { useSession, signIn } from 'next-auth/react';
import { usePuzzleGenerator } from '@/hooks/use-puzzle-generator';
import { CrosswordGrid } from '@/components/grid/crossword-grid';
import { ClueList } from '@/components/clues/clue-list';
import type { Puzzle, Direction } from '@/engine/types';

export default function CreatorPage() {
  const { generate, validateWord, ready, error: workerError } = usePuzzleGenerator();
  const { data: session } = useSession();
  const [puzzle, setPuzzle] = useState<Puzzle | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [sharing, setSharing] = useState(false);
  const [gridSize, setGridSize] = useState<5 | 7 | 13>(5);
  const [customWords, setCustomWords] = useState<string[]>(['', '', '']);
  const [wordErrors, setWordErrors] = useState<(string | null)[]>([null, null, null]);

  const handleSizeChange = (size: 5 | 7 | 13) => {
    setGridSize(size);
    setPuzzle(null);
    setShareUrl(null);
    setWordErrors(prev =>
      prev.map((err, i) => {
        const word = customWords[i];
        if (!word) return null;
        if (word.length > size) return `Too long for ${size}\u00d7${size}`;
        return err === `Too long for ${gridSize}\u00d7${gridSize}` ? null : err;
      })
    );
  };

  const handleWordChange = (index: number, value: string) => {
    const upper = value.toUpperCase().replace(/[^A-Z]/g, '');
    const newWords = [...customWords];
    newWords[index] = upper;
    setCustomWords(newWords);
  };

  const handleWordBlur = async (index: number, value: string) => {
    const upper = value.toUpperCase().replace(/[^A-Z]/g, '');
    const newWords = [...customWords];
    newWords[index] = upper;
    setCustomWords(newWords);

    const newErrors = [...wordErrors];
    if (upper === '') {
      newErrors[index] = null;
    } else if (upper.length < 3) {
      newErrors[index] = 'Too short (min 3)';
    } else if (upper.length > gridSize) {
      newErrors[index] = `Too long for ${gridSize}\u00d7${gridSize}`;
    } else {
      const valid = await validateWord(upper);
      newErrors[index] = valid ? null : 'Not in word list';
    }
    setWordErrors(newErrors);
  };

  const clearWord = (index: number) => {
    const newWords = [...customWords];
    newWords[index] = '';
    setCustomWords(newWords);
    const newErrors = [...wordErrors];
    newErrors[index] = null;
    setWordErrors(newErrors);
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);
    setShareUrl(null);
    try {
      const validCustomWords = customWords.filter((w, i) => w.length > 0 && !wordErrors[i]);
      const result = await generate({
        size: gridSize,
        customWords: validCustomWords.length > 0 ? validCustomWords : undefined,
      });
      setPuzzle(result);
    } catch (err) {
      setError((err as Error).message || "Couldn't generate a puzzle. Try again!");
    } finally {
      setGenerating(false);
    }
  };

  const handleShare = async () => {
    if (!puzzle) return;

    if (!session?.user) {
      signIn('google');
      return;
    }

    setSharing(true);
    try {
      const res = await fetch('/api/puzzles', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          grid: puzzle.grid,
          entries: puzzle.entries,
          size: puzzle.size,
        }),
      });

      if (!res.ok) throw new Error('Failed to share puzzle');

      const data = await res.json();
      setShareUrl(data.shareUrl);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSharing(false);
    }
  };

  const handleCopyLink = async () => {
    if (shareUrl) {
      await navigator.clipboard.writeText(shareUrl);
    }
  };

  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (ready && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, [ready]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleClueEdit = useCallback((number: number, direction: Direction, newClue: string) => {
    setPuzzle(prev => {
      if (!prev) return prev;
      return {
        ...prev,
        entries: prev.entries.map(e =>
          e.number === number && e.direction === direction ? { ...e, clue: newClue } : e
        ),
      };
    });
  }, []);

  // Derive inline status message
  let statusMessage: string | null = null;
  let statusType: 'success' | 'error' | 'info' = 'info';
  if (workerError) {
    statusMessage = workerError;
    statusType = 'error';
  } else if (error) {
    statusMessage = error;
    statusType = 'error';
  } else if (shareUrl) {
    statusMessage = shareUrl;
    statusType = 'success';
  } else if (puzzle && !generating) {
    statusMessage = 'Crossword generated! Edit words/clues below, or generate AI clues.';
    statusType = 'success';
  } else if (!ready) {
    statusMessage = 'Loading word list...';
    statusType = 'info';
  }

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 40 }}>
      <div className="toolbar">
        <div className="btn-group">
          <button
            className={`btn ${gridSize === 5 ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => handleSizeChange(5)}
            disabled={generating}
          >
            5×5
          </button>
          <button
            className={`btn ${gridSize === 7 ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => handleSizeChange(7)}
            disabled={generating}
          >
            7×7
          </button>
          <button
            className={`btn ${gridSize === 13 ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => handleSizeChange(13)}
            disabled={generating}
          >
            13×13
          </button>
        </div>

        <button
          className="btn btn-primary"
          onClick={handleGenerate}
          disabled={!ready || generating}
        >
          {generating ? 'Generating...' : 'Generate Puzzle'}
        </button>

        <button
          className="btn btn-secondary"
          onClick={handleShare}
          disabled={!puzzle || sharing}
        >
          {sharing ? 'Sharing...' : 'Share'}
        </button>

        {statusMessage && (
          <div className={`status-inline ${statusType}`}>
            {shareUrl ? (
              <span style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                <span style={{ flex: 1, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{shareUrl}</span>
                <button className="btn btn-secondary btn-sm" onClick={handleCopyLink} style={{ flexShrink: 0 }}>Copy</button>
              </span>
            ) : statusMessage}
          </div>
        )}
      </div>

      {puzzle && (
        <div className="crossword-card">
          <div className="crossword-card-grid">
            <h3 style={{ marginBottom: 24 }}>
              Preview <span className="text-hint" style={{ textTransform: 'none', letterSpacing: 'normal' }}>Click a letter to edit</span>
            </h3>
            <CrosswordGrid grid={puzzle.grid} entries={puzzle.entries} gridSize={puzzle.size} />
          </div>
          <div className="crossword-card-clues">
            <h3 style={{ marginBottom: 24 }}>Clues</h3>
            <ClueList entries={puzzle.entries} editable onClueEdit={handleClueEdit} />
          </div>
        </div>
      )}

      <div className="card">
        <h3 style={{ marginBottom: 24 }}>
          Custom Words <span className="text-hint" style={{ textTransform: 'none', letterSpacing: 'normal' }}>Optional</span>
        </h3>
        <div className="custom-words-row">
          {customWords.map((word, i) => (
            <div key={i} className="custom-word-input-wrapper">
              <div style={{ position: 'relative' }}>
                <input
                  className={`custom-word-input${wordErrors[i] ? ' input-error' : ''}`}
                  type="text"
                  placeholder={`Word ${i + 1}`}
                  value={word}
                  onChange={e => handleWordChange(i, e.target.value)}
                  onBlur={e => handleWordBlur(i, e.target.value)}
                  maxLength={gridSize}
                  disabled={generating}
                />
                {word && (
                  <button
                    className="custom-word-clear"
                    onClick={() => clearWord(i)}
                    tabIndex={-1}
                  >
                    &times;
                  </button>
                )}
              </div>
              {wordErrors[i] && (
                <div className="custom-word-error">{wordErrors[i]}</div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
