'use client';

import { useState, useCallback, useEffect, useRef } from 'react';
import { useSession, signIn } from 'next-auth/react';
import { usePuzzleGenerator } from '@/hooks/use-puzzle-generator';
import { CrosswordGrid } from '@/components/grid/crossword-grid';
import { SkeletonGrid } from '@/components/grid/skeleton-grid';
import { ClueList } from '@/components/clues/clue-list';
import type { Puzzle, Direction } from '@/engine/types';

export default function CreatorPage() {
  const { generate, validateWord, getClues, ready, error: workerError } = usePuzzleGenerator();
  const { data: session } = useSession();
  const [puzzle, setPuzzle] = useState<Puzzle | null>(null);
  const [generating, setGenerating] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [shareUrl, setShareUrl] = useState<string | null>(null);
  const [sharing, setSharing] = useState(false);
  const [gridSize, setGridSize] = useState<5 | 7 | 9>(5);
  const [customWords, setCustomWords] = useState<string[]>(['', '', '']);
  const [wordErrors, setWordErrors] = useState<(string | null)[]>([null, null, null]);
  const clueCache = useRef<Map<string, string[]>>(new Map());
  const [aiGeneratingKey, setAiGeneratingKey] = useState<string | null>(null);

  const handleSizeChange = (size: 5 | 7 | 9) => {
    if (size === gridSize) {
      handleGenerate();
      return;
    }
    setGridSize(size);
    setPuzzle(null);
    setShareUrl(null);
    setWordErrors(prev =>
      prev.map((err, i) => {
        const word = customWords[i];
        if (!word) return null;
        if (word.length > size) return `Too long for ${size}\u00d7${size}`;
        return err === `Too long for ${gridSize}\u00d7${gridSize}` ? null : err;
      })
    );
  };

  const handleWordChange = (index: number, value: string) => {
    const upper = value.toUpperCase().replace(/[^A-Z]/g, '');
    const newWords = [...customWords];
    newWords[index] = upper;
    setCustomWords(newWords);
  };

  const handleWordBlur = async (index: number, value: string) => {
    const upper = value.toUpperCase().replace(/[^A-Z]/g, '');
    const newWords = [...customWords];
    newWords[index] = upper;
    setCustomWords(newWords);

    const newErrors = [...wordErrors];
    if (upper === '') {
      newErrors[index] = null;
    } else if (upper.length < 3) {
      newErrors[index] = 'Too short (min 3)';
    } else if (upper.length > gridSize) {
      newErrors[index] = `Too long for ${gridSize}\u00d7${gridSize}`;
    } else {
      const valid = await validateWord(upper);
      newErrors[index] = valid ? null : 'Not in word list';
    }
    setWordErrors(newErrors);
  };

  const clearWord = (index: number) => {
    const newWords = [...customWords];
    newWords[index] = '';
    setCustomWords(newWords);
    const newErrors = [...wordErrors];
    newErrors[index] = null;
    setWordErrors(newErrors);
  };

  const handleGenerate = async () => {
    setGenerating(true);
    setError(null);
    setShareUrl(null);
    try {
      const validCustomWords = customWords.filter((w, i) => w.length > 0 && !wordErrors[i]);
      const result = await generate({
        size: gridSize,
        customWords: validCustomWords.length > 0 ? validCustomWords : undefined,
      });
      clueCache.current.clear();
      setPuzzle(result);
    } catch (err) {
      setError((err as Error).message || "Couldn't generate a puzzle. Try again!");
    } finally {
      setGenerating(false);
    }
  };

  const handleShare = async () => {
    if (!puzzle) return;

    if (!session?.user) {
      signIn('google');
      return;
    }

    setSharing(true);
    try {
      const res = await fetch('/api/puzzles', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          grid: puzzle.grid,
          entries: puzzle.entries,
          size: puzzle.size,
        }),
      });

      if (!res.ok) throw new Error('Failed to share puzzle');

      const data = await res.json();
      setShareUrl(data.shareUrl);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSharing(false);
    }
  };

  const handleCopyLink = async () => {
    if (shareUrl) {
      await navigator.clipboard.writeText(shareUrl);
    }
  };

  const hasAutoGenerated = useRef(false);
  useEffect(() => {
    if (ready && !hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, [ready]); // eslint-disable-line react-hooks/exhaustive-deps

  // Auto-generate when grid size changes
  useEffect(() => {
    if (ready && hasAutoGenerated.current) {
      handleGenerate();
    }
  }, [gridSize]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleClueEdit = useCallback((number: number, direction: Direction, newClue: string) => {
    setPuzzle(prev => {
      if (!prev) return prev;
      return {
        ...prev,
        entries: prev.entries.map(e =>
          e.number === number && e.direction === direction ? { ...e, clue: newClue } : e
        ),
      };
    });
  }, []);

  const handleClueRefresh = useCallback(async (number: number, direction: Direction) => {
    if (!puzzle) return;
    const entry = puzzle.entries.find(e => e.number === number && e.direction === direction);
    if (!entry?.answer) return;

    const word = entry.answer;
    let clues = clueCache.current.get(word);
    if (!clues) {
      const fetched = await getClues(word);
      clues = [...fetched];
      clueCache.current.set(word, clues);
    }
    if (clues.length === 0) return;

    const currentIndex = clues.indexOf(entry.clue);
    const nextIndex = (currentIndex + 1) % clues.length;
    handleClueEdit(number, direction, clues[nextIndex]);
  }, [puzzle, getClues, handleClueEdit]);

  const handleAiClue = useCallback(async (number: number, direction: Direction) => {
    if (!puzzle || !session?.user) return;
    const entry = puzzle.entries.find(e => e.number === number && e.direction === direction);
    if (!entry?.answer) return;

    const key = `${number}-${direction}`;
    setAiGeneratingKey(key);
    setError(null);

    try {
      // Ensure clue cache is populated from the worker BEFORE adding AI clue
      let cached = clueCache.current.get(entry.answer);
      if (!cached) {
        const fetched = await getClues(entry.answer);
        cached = [...fetched];
        clueCache.current.set(entry.answer, cached);
      }

      const res = await fetch('/api/clues/generate', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          word: entry.answer,
          existingClues: cached,
        }),
      });

      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || 'Failed to generate clue');
      }

      const { clue } = await res.json();
      handleClueEdit(number, direction, clue);

      // Append AI clue to the already-populated cache
      if (!cached.includes(clue)) {
        cached.push(clue);
      }
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setAiGeneratingKey(null);
    }
  }, [puzzle, session, handleClueEdit, getClues]);

  // Derive inline status message
  let statusMessage: string | null = null;
  let statusType: 'success' | 'error' | 'info' = 'info';
  if (workerError) {
    statusMessage = workerError;
    statusType = 'error';
  } else if (error) {
    statusMessage = error;
    statusType = 'error';
  } else if (shareUrl) {
    statusMessage = shareUrl;
    statusType = 'success';
  } else if (puzzle && !generating) {
    statusMessage = 'Crossword generated! Edit words/clues below, or generate AI clues.';
    statusType = 'success';
  } else if (!ready) {
    statusMessage = 'Loading word list...';
    statusType = 'info';
  }

  return (
    <div className="page-stack">
      <div className="toolbar">
        <div className="btn-group">
          <button
            className={`btn ${gridSize === 5 ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => handleSizeChange(5)}
            disabled={generating}
          >
            5×5
          </button>
          <button
            className={`btn ${gridSize === 7 ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => handleSizeChange(7)}
            disabled={generating}
          >
            7×7
          </button>
          <button
            className={`btn ${gridSize === 9 ? 'btn-primary' : 'btn-secondary'}`}
            onClick={() => handleSizeChange(9)}
            disabled={generating}
          >
            9×9
          </button>
        </div>

        <button
          className="btn btn-primary"
          onClick={handleGenerate}
          disabled={!ready || generating}
        >
          {generating ? 'Generating...' : 'Generate Puzzle'}
        </button>

        <button
          className="btn btn-secondary"
          onClick={handleShare}
          disabled={!puzzle || sharing}
        >
          {sharing ? 'Sharing...' : 'Share'}
        </button>

        {statusMessage && (
          <div className={`status ${statusType}`}>
            {shareUrl ? (
              <span className="share-url">
                <span className="share-url-text">{shareUrl}</span>
                <button className="btn btn-secondary btn-sm" onClick={handleCopyLink}>Copy</button>
              </span>
            ) : statusMessage}
          </div>
        )}
      </div>

      {generating && (
        <div className="card crossword-card">
          <div className="crossword-card-grid">
            <h3>Preview</h3>
            <SkeletonGrid gridSize={gridSize} />
          </div>
          <div className="crossword-card-clues">
            <h3>Clues</h3>
            <div className="clue-creator">
              <div className="clue-section">
                <h4>Across</h4>
                {[1, 2, 3].map(n => (
                  <div className="clue-row" key={n}>
                    <input className="input" disabled />
                  </div>
                ))}
              </div>
              <div className="clue-section">
                <h4>Down</h4>
                {[1, 2, 3].map(n => (
                  <div className="clue-row" key={n}>
                    <input className="input" disabled />
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {puzzle && !generating && (
        <div className="card crossword-card">
          <div className="crossword-card-grid">
            <h3>
              Preview <span className="text-hint">Click a letter to edit</span>
            </h3>
            <CrosswordGrid grid={puzzle.grid} entries={puzzle.entries} gridSize={puzzle.size} />
          </div>
          <div className="crossword-card-clues">
            <h3>Clues</h3>
            <ClueList entries={puzzle.entries} editable onClueEdit={handleClueEdit} onClueRefresh={handleClueRefresh} onAiClue={handleAiClue} aiGeneratingKey={aiGeneratingKey} />
          </div>
        </div>
      )}

      <div className="card">
        <h3>
          Custom Words <span className="text-hint">Optional</span>
        </h3>
        <div className="custom-words-row">
          {customWords.map((word, i) => (
            <div key={i} className="custom-word-input-wrapper">
                <input
                  className={`input custom-word-input${wordErrors[i] ? ' input-error' : ''}`}
                  type="text"
                  placeholder={`Word ${i + 1}`}
                  value={word}
                  onChange={e => handleWordChange(i, e.target.value)}
                  onBlur={e => handleWordBlur(i, e.target.value)}
                  maxLength={gridSize}
                  disabled={generating}
                />
                {word && (
                  <button
                    className="custom-word-clear"
                    onClick={() => clearWord(i)}
                    tabIndex={-1}
                  >
                    &times;
                  </button>
                )}
              {wordErrors[i] && (
                <div className="custom-word-error">{wordErrors[i]}</div>
              )}
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
